"""create pipeline_jobs table

Revision ID: 46e9e861793c
Revises: 77be71dae067
Create Date: 2026-03-22 00:06:46.671546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = '46e9e861793c'
down_revision: Union[str, Sequence[str], None] = '77be71dae067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('checkpoint', sa.Integer(), nullable=False),
    sa.Column('config', JSONB(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        "uq_one_active_job_per_user",
        "pipeline_jobs",
        ["user_id"],
        unique=True,
        postgresql_where=text("status IN ('pending', 'claimed', 'running')"),
    )
    op.create_index(
        "idx_pipeline_jobs_claimable",
        "pipeline_jobs",
        ["created_at"],
        postgresql_where=text("status = 'pending'"),
    )
    op.create_index(
        "idx_pipeline_jobs_stale",
        "pipeline_jobs",
        ["heartbeat_at"],
        postgresql_where=text("status = 'running'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_pipeline_jobs_stale", table_name="pipeline_jobs")
    op.drop_index("idx_pipeline_jobs_claimable", table_name="pipeline_jobs")
    op.drop_index("uq_one_active_job_per_user", table_name="pipeline_jobs")
    op.drop_table('pipeline_jobs')
    # ### end Alembic commands ###
