"""add research_briefs evidence_cards blackboard tables

Revision ID: d4dfd7814e8f
Revises: 81bf14b0a537
Create Date: 2026-03-18 15:28:26.000825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4dfd7814e8f'
down_revision: Union[str, Sequence[str], None] = '81bf14b0a537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackboard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('glossary', sa.JSON(), nullable=False),
    sa.Column('concept_ownership', sa.JSON(), nullable=False),
    sa.Column('coverage_map', sa.JSON(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('source_log', sa.JSON(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('evidence_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('section_position', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('source_tier', sa.Integer(), nullable=False),
    sa.Column('passage', sa.Text(), nullable=False),
    sa.Column('retrieved_date', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('caveat', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_briefs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('section_position', sa.Integer(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('source_policy', sa.JSON(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('ungrounded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sections', sa.Column('citations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'citations')
    op.drop_column('courses', 'ungrounded')
    op.drop_table('research_briefs')
    op.drop_table('evidence_cards')
    op.drop_table('blackboard')
    # ### end Alembic commands ###
