"""add academic fields to evidence_cards

Revision ID: fa3f0c52cbd9
Revises: 8fb5f073bb71
Create Date: 2026-03-28 20:49:50.555346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3f0c52cbd9'
down_revision: Union[str, Sequence[str], None] = '8fb5f073bb71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_cards', sa.Column('is_academic', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('evidence_cards', sa.Column('academic_authors', sa.Text(), nullable=True))
    op.add_column('evidence_cards', sa.Column('academic_year', sa.Integer(), nullable=True))
    op.add_column('evidence_cards', sa.Column('academic_venue', sa.Text(), nullable=True))
    op.add_column('evidence_cards', sa.Column('academic_doi', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_cards', 'academic_doi')
    op.drop_column('evidence_cards', 'academic_venue')
    op.drop_column('evidence_cards', 'academic_year')
    op.drop_column('evidence_cards', 'academic_authors')
    op.drop_column('evidence_cards', 'is_academic')
    # ### end Alembic commands ###
