#set page(
  margin: (top: 2.5cm, bottom: 2.5cm, left: 3cm, right: 3cm),
  numbering: "1",
  number-align: center,
)

#set text(font: "New Computer Modern", size: 11pt)
#set par(justify: true, leading: 0.75em)
#set heading(numbering: "1.")

#show heading.where(level: 1): set text(size: 18pt, weight: "bold")
#show heading.where(level: 2): set text(size: 14pt, weight: "semibold")
#show heading.where(level: 3): set text(size: 12pt, weight: "semibold")

#let render_cover(title, generated_at) = [
  #set page(numbering: none)
  #align(center)[
    #v(25%)
    #text(size: 28pt, weight: "bold")[#title]
    \
    #v(1.1em)
    #text(size: 12pt, fill: luma(90))[Generated by agent-learn]
    \
    #v(0.8em)
    #generated_at
  ]
  #pagebreak()
  #set page(numbering: "1", number-align: center)
]

#let render_section(title, body) = [
  #pagebreak()
  = #title
  #body
]

#let render_references(body) = [
  #pagebreak()
  = References
  #body
]
